version: '3.9'

services:

  # =========================
  # BACKEND
  # =========================

  api-gateway:
    build: ./api-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MS_DB_URL: postgres://postgres:postgres@postgres:5432/microservices_db
      JWT_SECRET: secret
    volumes:
    - ./api-gateway:/app
    - /app/node_modules
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_started

  auth-service:
    build: ./auth-service
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      MS_DB_URL: postgres://postgres:postgres@postgres:5432/microservices_db
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/auth_db
      JWT_SECRET: secret
    volumes:
    - ./auth-service:/app
    - /app/node_modules
    depends_on:
      postgres:
        condition: service_started

  realtime-gateway:
    build: ./realtime-gateway
    restart: unless-stopped
    ports:
      - "4500:4500"
    environment:
      JWT_SECRET: secret
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/rule_db
      MS_DB_URL: postgres://postgres:postgres@postgres:5432/microservices_db
    volumes:
    - ./realtime-gateway:/app
    - /app/node_modules
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_started

  webhook-service:
    build: ./webhook-service
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/rule_db
      MS_DB_URL: postgres://postgres:postgres@postgres:5432/microservices_db
    volumes:
    - ./webhook-service:/app
    - /app/node_modules
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_started
  
  execution-service:
    build: ./execution-service
    restart: unless-stopped
    ports:
      - "5500:5500"
    volumes:
    - ./execution-service:/app
    - ./execution-service/src/logs:/app/src/logs
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/rule_db
      MS_DB_URL: postgres://postgres:postgres@postgres:5432/microservices_db
    depends_on:
      postgres:
        condition: service_started
  
  rule-service:
    build: ./rule-service
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/rule_db
      MS_DB_URL: postgres://postgres:postgres@postgres:5432/microservices_db
    volumes:
      - ./rule-service:/app
      - ./rule-service/src/logs:/app/src/logs
    depends_on:
      postgres:
        condition: service_started

  notification-service:
    build: ./notification-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MS_DB_URL: postgres://postgres:postgres@postgres:5432/microservices_db
    volumes:
      - ./notification-service:/app
      - ./notification-service/src/logs:/app/src/logs
    depends_on:
      postgres:
        condition: service_started
  
  user-service:
    build: ./user-service
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      MS_DB_URL: postgres://postgres:postgres@postgres:5432/microservices_db
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/user_db
    volumes:
      - ./user-service:/app
      - ./user-service/src/logs:/app/src/logs
    depends_on:
      postgres:
        condition: service_started
  
  # =========================
  # DBS
  # =========================

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
    - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    

  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: backend-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  # =========================
  # FRONTEND
  # =========================

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - api-gateway
  
  # =========================
  # MONITORING
  # =========================
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api-gateway
      - auth-service
      - realtime-gateway
      - webhook-service

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3031:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - api-gateway
      - auth-service
      - realtime-gateway
      - webhook-service
      - prometheus

volumes:
  postgres_data:
  pgadmin_data:    
  redis_data:
  prometheus_data:
  grafana_data:
