global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:3000"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:4000"]

  - job_name: "realtime-gateway"
    static_configs:
      - targets: ["realtime-gateway:4500"]

  - job_name: "webhook-service"
    static_configs:
      - targets: ["webhook-service:5000"]