name: CI

on:
    push:
        branches:
            - main

jobs:

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm install

      - run: npm run build

  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .

  docker:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Build Docker
          run: docker build -t automation-app .