name: CI

on:
    push:
        branches:
            - main

jobs:

  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .

  docker:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Build Docker
          run: docker compose build 