name: CI

on:
  push:
    branches:
      - main
      
jobs:

  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
  
  docker:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Wait services
        run: sleep 20

      - name: Show logs
        run: docker compose logs

      - name: Run tests inside containers
        run: |
          docker compose exec -T api-gateway npm test
          docker compose exec -T webhook-service npm test
          docker compose exec -T auth-service npm test
          docker compose exec -T frontend npm test

      - name: Run python tests
        run: |
          docker compose exec -T rule-service python -m unittest discover -s tests
          docker compose exec -T execution-service python -m unittest discover -s tests
          docker compose exec -T user-service python -m unittest discover -s tests
          docker compose exec -T notification-service python -m unittest discover -s tests
      - name: Stop services
        if: always()
        run: docker compose down


  